export const SET_USER_SIGNING_IN = "SET_USER_SIGNING_IN";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const HANDLE_USER_SIGNING_IN_ERROR = "HANDLE_USER_SIGNING_IN_ERROR";
export const REQUEST_LOGOUT = "REQUEST_LOGOUT";

export const SET_USER_SIGNING_UP = "SET_USER_SIGNING_UP";
export const HANDLE_USER_SIGNING_UP_SUCCESS = "HANDLE_USER_SIGNING_UP_SUCCESS";
export const HANDLE_USER_SIGNING_UP_ERROR = "HANDLE_USER_SIGNING_UP_ERROR";

export const SET_USER_FRIDGES_LOADING = "SET_USER_FRIDGES_LOADING";
export const SET_USER_FRIDGES = "SET_USER_FRIDGES";
export const HANDLE_USER_FRIDGES_LOADING_ERROR =
  "HANDLE_USER_FRIDGES_LOADING_ERROR";

export const SET_ADDING_FRIDGE = "SET_ADDING_FRIDGE";
export const SET_ADDING_FRIDGE_DONE = "SET_ADDING_FRIDGE_DONE";

export const SET_DELETING_FRIDGE = "SET_DELETING_FRIDGE";
export const SET_DELETING_FRIDGE_DONE = "SET_DELETING_FRIDGE_DONE";

export const SET_INVITING_USER = "SET_INVITING_USER";
export const SET_INVITING_USER_DONE = "SET_INVITING_USER_DONE";

export const ACCEPT_FRIDGE_INVITATION = "ACCEPT_FRIDGE_INVITATION";
export const DECLINE_FRIDGE_INVITATION = "DECLINE_FRIDGE_INVITATION";

export const SET_USER_RECIPES_LOADING = "SET_USER_RECIPES_LOADING";
export const GET_USER_RECIPES = "GET_USER_RECIPES";
export const HANDLE_USER_RECIPES_LOADING_ERROR =
  "HANDLE_USER_RECIPES_LOADING_ERROR";

export const SET_ADDING_RECIPE = "SET_ADDING_RECIPE";
export const SET_ADDING_RECIPE_DONE = "SET_ADDING_RECIPE_DONE";

export const SET_DELETING_RECIPE = "SET_DELETING_RECIPE";
export const SET_DELETING_RECIPE_DONE = "SET_DELETING_RECIPE_DONE";

export const SET_SUFFICIENT_INGREDIENTS_LOADING =
  "SET_SUFFICIENT_INGREDIENTS_LOADING";
export const SET_SUFFICIENT_INGREDIENTS_LOADING_ENDED =
  "SET_SUFFICIENT_INGREDIENTS_LOADING_ENDED";

export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const GET_INGREDIENT_CATEGORIES = "GET_INGREDIENT_CATEGORIES";
