export const SET_USER_SIGNING_IN = "SET_USER_SIGNING_IN";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const HANDLE_USER_SIGNING_IN_ERROR = "HANDLE_USER_SIGNING_IN_ERROR";
export const REQUEST_LOGOUT = "REQUEST_LOGOUT";

export const SET_USER_SIGNING_UP = "SET_USER_SIGNING_UP";
export const HANDLE_USER_SIGNING_UP_SUCCESS = "HANDLE_USER_SIGNING_UP_SUCCESS";
export const HANDLE_USER_SIGNING_UP_ERROR = "HANDLE_USER_SIGNING_UP_ERROR";

export const SET_USER_FRIDGES_LOADING = "SET_USER_FRIDGES_LOADING";
export const SET_USER_FRIDGES = "SET_USER_FRIDGES";
export const HANDLE_USER_FRIDGES_LOADING_ERROR =
  "HANDLE_USER_FRIDGES_LOADING_ERROR";

export const SET_USER_RECIPES_LOADING = "SET_USER_RECIPES_LOADING";
export const GET_USER_RECIPES = "GET_USER_RECIPES";
export const HANDLE_USER_RECIPES_LOADING_ERROR =
  "HANDLE_USER_RECIPES_LOADING_ERROR";

export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const GET_INGREDIENT_CATEGORIES = "GET_INGREDIENT_CATEGORIES";
